Update game_setup.cr
Updated the thing
Current issues - getting the following error when attempting to run:
In game_setup.cr:48:21

 48 | input_names = input_loops(input_sheep_num, "name")
                    ^----------
Error: no overload matches 'input_loops' with types (Int32 | String | Nil), String

Overloads are:
 - input_loops(num_sheep : Int32, input_type : String)
Couldn't find overloads for these types:
 - input_loops(num_sheep : String, input_type : String)
 - input_loops(num_sheep : Nil, input_type : String)

Need to fix this